#!/usr/bin/env python3
__author__ = "Mario Lukas"
__copyright__ = "Copyright 2017"
__license__ = "GPL v2"
__maintainer__ = "Mario Lukas"
__email__ = "info@mariolukas.de"

import fabscan


def main():
    # Do not run avrdude here: it reserves the serial port for ~1 minute, uses the
    # FabScanPi HAT profile (-p m328p), and conflicts with RAMPS/Mega2560 setups.
    # Flash firmware manually when needed; optional probes belong behind config.
    fabscan.main()


if __name__ == "__main__":
    main()
